### PR TITLE
project submission

### PR DESCRIPTION
**Pull request by kmakai**
please and thank you.

### CODE REVIEW

**Review by TheCSharpAcademy — CHANGES_REQUESTED** [review]
@kmakai The project is looking good, I'm just struggling to get the drinks in categories that have special characters: 
image

**Comment by kmakai** [comment]
thanks, I never thought to even check those I will check it out.

**Comment by kmakai** [comment]
I have updated it the validation was only accepting letters for categories I changed it to leave out '/' character

**Comment by TheCSharpAcademy** [comment]
@kmakai I'll approve it because I don't want to be overly strict, but you also need to allow white spaces 
image

**Pull request merged**
