### PR TITLE
Drinks Project

### PR DESCRIPTION
**Pull request by Fennikko**
I look forward to any feedback you can provide!

### CODE REVIEW

**Comment by Fennikko** [comment]
Unnecessary using of system.net is a false positive in codacy.

**Review by VocalNight — CHANGES_REQUESTED** [review]
Good job on the project! Everything looks great.

Just 2 things would make this project better

* When you input the name of the category, unless you properly input the name of the category with capital letters, the application will not validate your input correctly.

image

Check the ToUpper() function and how you can use it to compare strings.

* The drinks list when you select "ordinary drinks" is way too long and covers the entire UI, making the user have to scroll down quite a bit to check the prompt. See if you could find a way to paginate the list or make it smaller 

image

**Comment by Fennikko** [comment]
Requested changes have been made

**Review by VocalNight — APPROVED** [review]
Everything looks good now. Good job!
Looking forward to your next projects.

**Pull request closed without merging**
