### PR TITLE
Project finished.

### PR DESCRIPTION
**Pull request by jollejonas**
Project finished. Looking forward to your review.

### CODE REVIEW

**Review by kimfom01 — CHANGES_REQUESTED** [review]
Hello, congratulations on submitting your project! :confetti_ball: 

While I was review it, I encountered a weird issue as you will see from the video linked below :thinking: 
[Screencast from 07-06-2024 07:21:41 PM.webm](https://github.com/TheCSharpAcademy/CodeReviews.Console.Drinks/assets/57032138/a77752a5-df92-4213-bdc7-4533c504491d)
I think this is because all the drinks are returning null after the call to SelectDrink :sweat_smile: 

Can you investigate and fix this? I can't continue the review without this working :pray:

**Comment by jollejonas** [comment]
I figured it out. I had changed the casing in my model to pascal case, because codacy static code analysis called my camel casing a minor issue. This made a mismatch between my property names and the JSON names. I have added a JSONPropertyName to all properties in my drink model which have fixed the issue.

Thank you. 😄

**Review by kimfom01 — CHANGES_REQUESTED** [review]
Here goes my review :smile: 

ApiService: `GetAsync<T>` should return a `Task<T?>` as there is a possibility of returning null, it should be clearly stated in your method definition. Also `JsonSerializer.Deserialize<T>` method usually returns a nullable result therefore the generic `T result` should be `T? result` :pray:

DrinksService: At line 8, I see you defined and instantiated `ApiService`. By convention, a private keyword should be prepended at the begining to clearly specify that it is a private field so it would look like `private ApiService apiService = new ApiService("your base url");` :blush: 

DrinksService: At line 25, you forgot to update the `strCategory` to match the fix you made earlier so it should be `c.StrCategory` otherwise your code doesn't compile as it is :sweat_smile:

General advice:
- If a method can return `null` or `default`, it is recommended to explicitly specify that it does return a `null`. It will save you a ton of headache in the long run.
- If a method accepts a type that can be `null`, then it should be specified that it does and then handled accordingly.
- Prefer file-scoped namespaces over the regular namespaces. It helps to reduce nesting of your code and enhances the readability. I believe you must've been told this a ton of times here on The C# Academy :sweat_smile:

Alright do these and I will approve your project!

**Comment by jollejonas** [comment]
Thanks a lot for the feedback. I have updated the code accordingly and made a few extra changes. 😄

**Review by kimfom01 — APPROVED** [review]
Excellent! :grin: everything looks okay now so I'll approve it! Congratulations and looking forward to your next project :confetti_ball:

**Pull request merged**
