### PR TITLE
Finished the project

### PR DESCRIPTION
**Pull request by eddyfadeev**
Hello, I just finished the project. Thank you for your review!

### CODE REVIEW

**Comment by Jinboi** [comment]
Hi @eddyfadeev ,

Thank you for submitting your project!

Your project looks great! 

I'll mark this as completed. Please move on to the next project! 

Thank you and Happy Coding! 

Cheers,
-Youngwoo

**Comment by eddyfadeev** [comment]
Hi @Jinboi ,
Thank you for the review! 

Should I close the request or you will merge it? 

Have a nice day!

Regards,
Eduard

**Comment by Jinboi** [comment]
I need to merge it. I've never done it in TCSA so let me just figure that out and merge it shortly hahaha

**Comment by eddyfadeev** [comment]
Got ya, best of luck then 😁

**Pull request merged**
