### PR TITLE
User: Lonchanick | Project: Drinks

### PR DESCRIPTION
**Pull request by lonchanick**
Drinks console project pull request

### CODE REVIEW

**Comment by lonchanick** [comment]
Hello Pablo
here Diego waiting for review :) Thanks (Y)!

**Comment by lonchanick** [comment]
Pablo, Codacy tool is asking me for to change the objects properties name but, if I change it they would not match with the Json field name ... so I just let it as they are in the project.
Sorry my spanglis :|

**Comment by TheCSharpAcademy** [comment]
Hey there! I'm approving the project since you demonstrated you can call an API, but I think it would be a nice challenge to show the drink detail with better property names instead of the ones in the raw json: 

image

**Comment by lonchanick** [comment]
Oka Thanks :)

**Pull request merged**
