### PR TITLE
Finished Drink-Info project

### PR DESCRIPTION
**Pull request by N-Endy**
I learnt a lot from this project, even the risks of using "git rebase"

### CODE REVIEW

**Comment by stevietv** [comment]
Hey @N-Endy  - congrats on completing this one, its approved ✅ 
The only feedback I would have as a user would be to not build in artificial Sleeps, we want our apps to be snappy 😉 

Before it can be merged though I would need you to revert commit 09a6801 - otherwise everyone else's submissions would be deleted! You should in future only commit things within your sub directory.

**Review by stevietv — CHANGES_REQUESTED** [review]
Please revert the final commit before we merge it.

**Comment by N-Endy** [comment]
Thank you Stevie.

I'll take note of the artificial Sleeps. I have also reverted the
commit 09a6801

**Review by stevietv — APPROVED** [review]

**Comment by stevietv** [comment]
@TheCSharpAcademy - please merge this one as its approved - codacy is blocking it from being merged.

**Pull request closed without merging**
