### PR TITLE
Merge Request: Finished Base Project + Challenges; 

### PR DESCRIPTION
**Pull request by K-MYR**
Thank you for reviewing my code!
I tried out new stuff like async and interfaces. Even if it did not really make sense i just wanted to try to implement those things to get familiar with them. 
Hope you have a great day!

### CODE REVIEW

**Comment by K-MYR** [comment]
Am i doing something wrong or why is codacy always telling me that "using System Configuration" is unnecassary? 😅

**Comment by TheCSharpAcademy** [comment]
> Am i doing something wrong or why is codacy always telling me that "using System Configuration" is unnecassary? 😅

Don't worry, Codacy is dumb sometimes 😂

**Comment by TheCSharpAcademy** [comment]
@K-MYR Well done! Great project!

**Comment by K-MYR** [comment]
> > Am i doing something wrong or why is codacy always telling me that "using System Configuration" is unnecassary? 😅
> 
> Don't worry, Codacy is dumb sometimes 😂

Haha alright! XD

**Comment by K-MYR** [comment]
> @K-MYR Well done! Great project!

Thank you so much! I really appreciate it! :)

**Pull request merged**
