### PR TITLE
Drinks info console app

### PR DESCRIPTION
**Pull request by ngalantino**
Ready for code review.

### CODE REVIEW

**Comment by hasona23** [comment]
Hi @ngalantino  how are you. great work finishing the drinks info but there are a few Mistakes that should be corrected. I'll classify them as (Critical(Can't accept)/Mild(Accepted but preferable to fix))
--Critical--
1- The instruction window and ingredients aren't clear. 
image
2- The Readme only consist of 5 links of resources that you didnt even specify what is it for. Please make links cleare using [MyLink](Url) and add few details about the project like what it does how it was made and you might talk about challenges you faced and things you learned
--Mild--
1- An error that was repeated 
image
since you are going to return  the list in the end then remove it from the if statemnt. the if statement will just edit it 
2- Dont put sln in same folder as .csproj instead so when making the project untick the put solution in same folder.
3- Also in drink details it is easier to make json propery for them for instance if the drink has name in json then make property name and same for other ingreidents. something like this  ```  [property: JsonPropertyName("strDrink")] string Name,
        [property: JsonPropertyName("strCategory")] string Category,
        [property: JsonPropertyName("strIngredient1")] string? Ingredient1,
        [property: JsonPropertyName("strIngredient2")] string? Ingredient2,
        [property: JsonPropertyName("strIngredient3")] string? Ingredient3,```
4- use async and learn about async and tasks. i know the scope of this project isnt much but in future and realworld projects you will deal with multiple calls at the same time so using async would save time and not block the main thread.
5- lastly you have 3 classes that uses this``` [JsonProperty("drinks")]

public List<Category> CategoriesList { get; set; }``` try to avoid repetition instead have a drink class with category and details and name and everythings then instead of having 6 classes you would have only do Drinks and drink.

Finishing the critical ones would make the project approvable.
Thanks 😄

**Review by ghost — CHANGES_REQUESTED** [review]
.

**Comment by hasona23** [comment]
If you wany you might use external use to help you make the readme

**Comment by ngalantino** [comment]
@hasona23 

Fixed the critical errors :) My readme file did not have the .md file extension which is why I was having trouble with the markdown rendering.

**Review by ghost — APPROVED** [review]
Hi @ngalantino thanks for doing changes. the drinks app better now and the README.md is more readable than before. I would suggest the if you want to use spectre console to make the categories and drinks as list ( prompt Selection ) but anyway 🎉 congratulations on finishing the project. i am going to approve it

**Pull request closed without merging**
